bottle: BOTTLE
cup: CUP
plate: PLATE
chair: CHAIR
table: TABLE
spoon: SPOON
knife: KNIFE
bowl: BOWL
fork: FORK
book: BOOK
teddy_bear: TEDDY_BEAR
spray_bottle: SPRAY_BOTTLE
pot: POT

# YCB classes
master_chef_can: YCB_002_MASTER_CHEF_CAN
cracker_box: YCB_003_CRACKER_BOX
sugar_box: YCB_004_SUGAR_BOX
tomato_soup_can: YCB_005_TOMATO_SOUP_CAN
mustard_bottle: YCB_006_MUSTARD_BOTTLE
tuna_fish_can: YCB_007_TUNA_FISH_CAN
pudding_box: YCB_008_PUDDING_BOX
gelatin_box: YCB_009_GELATIN_BOX
potted_meat_can: YCB_010_POTTED_MEAT_CAN
banana: YCB_011_BANANA
strawberry: YCB_012_STRAWBERRY
apple: YCB_013_APPLE
lemon: YCB_014_LEMON
peach: YCB_015_PEACH
pear: YCB_016_PEAR
orange: YCB_017_ORANGE
plum: YCB_018_PLUM
pitcher_base: YCB_019_PITCHER_BASE
bleach_cleanser: YCB_021_BLEACH_CLEANSER
windex_bottle: YCB_022_WINDEX_BOTTLE
bowl: YCB_024_BOWL
mug: YCB_025_MUG
sponge: YCB_026_SPONGE
skillet: YCB_027_SKILLET
skillet_lid: YCB_028_SKILLET_LID
plate: YCB_029_PLATE
fork: YCB_030_FORK
spoon: YCB_031_SPOON
knife: YCB_032_KNIFE
spatula: YCB_033_SPATULA
power_drill: YCB_035_POWER_DRILL
wood_block: YCB_036_WOOD_BLOCK
scissors: YCB_037_SCISSORS
padlock: YCB_038_PADLOCK
large_marker: YCB_040_LARGE_MARKER
adjustable_wrench: YCB_042_ADJUSTABLE_WRENCH
phillips_screwdriver: YCB_043_PHILLIPS_SCREWDRIVER
flat_screwdriver: YCB_044_FLAT_SCREWDRIVER
hammer: YCB_048_HAMMER
medium_clamp: YCB_050_MEDIUM_CLAMP
large_clamp: YCB_051_LARGE_CLAMP
extra_large_clamp: YCB_052_EXTRA_LARGE_CLAMP
mini_soccer_ball: YCB_053_MINI_SOCCER_BALL
softball: YCB_054_SOFTBALL
baseball: YCB_055_BASEBALL
tennis_ball: YCB_056_TENNIS_BALL
racquetball: YCB_057_RACQUETBALL
golf_ball: YCB_058_GOLF_BALL
chain: YCB_059_CHAIN
foam_brick: YCB_061_FOAM_BRICK
dice: YCB_062_DICE
a_marbles: YCB_063_A_MARBLES
b_marbles: YCB_063_B_MARBLES
a_cups: YCB_065_A_CUPS
b_cups: YCB_065_B_CUPS
c_cups: YCB_065_C_CUPS
d_cups: YCB_065_D_CUPS
e_cups: YCB_065_E_CUPS
f_cups: YCB_065_F_CUPS
g_cups: YCB_065_G_CUPS
h_cups: YCB_065_H_CUPS
i_cups: YCB_065_I_CUPS
j_cups: YCB_065_J_CUPS
a_colored_wood_blocks: YCB_070_A_COLORED_WOOD_BLOCKS
b_colored_wood_blocks: YCB_070_B_COLORED_WOOD_BLOCKS
nine_hole_peg_test: YCB_071_NINE_HOLE_PEG_TEST
a_toy_airplane: YCB_072_A_TOY_AIRPLANE
b_toy_airplane: YCB_072_B_TOY_AIRPLANE
c_toy_airplane: YCB_072_C_TOY_AIRPLANE
d_toy_airplane: YCB_072_D_TOY_AIRPLANE
e_toy_airplane: YCB_072_E_TOY_AIRPLANE
a_lego_duplo: YCB_073_A_LEGO_DUPLO
b_lego_duplo: YCB_073_B_LEGO_DUPLO
c_lego_duplo: YCB_073_C_LEGO_DUPLO
d_lego_duplo: YCB_073_D_LEGO_DUPLO
e_lego_duplo: YCB_073_E_LEGO_DUPLO
f_lego_duplo: YCB_073_F_LEGO_DUPLO
g_lego_duplo: YCB_073_G_LEGO_DUPLO
rubiks_cube: YCB_077_RUBIKS_CUBE
