bottle: BOTTLE
cup: CUP
plate: PLATE
chair: CHAIR
table: TABLE
spoon: SPOON
knife: KNIFE
bowl: BOWL
fork: FORK
book: BOOK
teddy_bear: TEDDY_BEAR
spray_bottle: SPRAY_BOTTLE
pot: POT
ycb_002_master_chef_can: YCB_002_MASTER_CHEF_CAN
ycb_003_cracker_box: YCB_003_CRACKER_BOX
ycb_004_sugar_box: YCB_004_SUGAR_BOX
ycb_005_tomato_soup_can: YCB_005_TOMATO_SOUP_CAN
ycb_006_mustard_bottle: YCB_006_MUSTARD_BOTTLE
ycb_007_tuna_fish_can: YCB_007_TUNA_FISH_CAN
ycb_008_pudding_box: YCB_008_PUDDING_BOX
ycb_009_gelatin_box: YCB_009_GELATIN_BOX
ycb_010_potted_meat_can: YCB_010_POTTED_MEAT_CAN
ycb_011_banana: YCB_011_BANANA
ycb_012_strawberry: YCB_012_STRAWBERRY
ycb_013_apple: YCB_013_APPLE
ycb_014_lemon: YCB_014_LEMON
ycb_015_peach: YCB_015_PEACH
ycb_016_pear: YCB_016_PEAR
ycb_017_orange: YCB_017_ORANGE
ycb_018_plum: YCB_018_PLUM
ycb_019_pitcher_base: YCB_019_PITCHER_BASE
ycb_021_bleach_cleanser: YCB_021_BLEACH_CLEANSER
ycb_022_windex_bottle: YCB_022_WINDEX_BOTTLE
ycb_024_bowl: YCB_024_BOWL
ycb_025_mug: YCB_025_MUG
ycb_026_sponge: YCB_026_SPONGE
ycb_027_skillet: YCB_027_SKILLET
ycb_028_skillet_lid: YCB_028_SKILLET_LID
ycb_029_plate: YCB_029_PLATE
ycb_030_fork: YCB_030_FORK
ycb_031_spoon: YCB_031_SPOON
ycb_032_knife: YCB_032_KNIFE
ycb_033_spatula: YCB_033_SPATULA
ycb_035_power_drill: YCB_035_POWER_DRILL
ycb_036_wood_block: YCB_036_WOOD_BLOCK
ycb_037_scissors: YCB_037_SCISSORS
ycb_038_padlock: YCB_038_PADLOCK
ycb_040_large_marker: YCB_040_LARGE_MARKER
ycb_042_adjustable_wrench: YCB_042_ADJUSTABLE_WRENCH
ycb_043_phillips_screwdriver: YCB_043_PHILLIPS_SCREWDRIVER
ycb_044_flat_screwdriver: YCB_044_FLAT_SCREWDRIVER
ycb_048_hammer: YCB_048_HAMMER
ycb_050_medium_clamp: YCB_050_MEDIUM_CLAMP
ycb_051_large_clamp: YCB_051_LARGE_CLAMP
ycb_052_extra_large_clamp: YCB_052_EXTRA_LARGE_CLAMP
ycb_053_mini_soccer_ball: YCB_053_MINI_SOCCER_BALL
ycb_054_softball: YCB_054_SOFTBALL
ycb_055_baseball: YCB_055_BASEBALL
ycb_056_tennis_ball: YCB_056_TENNIS_BALL
ycb_057_racquetball: YCB_057_RACQUETBALL
ycb_058_golf_ball: YCB_058_GOLF_BALL
ycb_059_chain: YCB_059_CHAIN
ycb_061_foam_brick: YCB_061_FOAM_BRICK
ycb_062_dice: YCB_062_DICE
ycb_063_a_marbles: YCB_063_A_MARBLES
ycb_063_b_marbles: YCB_063_B_MARBLES
ycb_065_a_cups: YCB_065_A_CUPS
ycb_065_b_cups: YCB_065_B_CUPS
ycb_065_c_cups: YCB_065_C_CUPS
ycb_065_d_cups: YCB_065_D_CUPS
ycb_065_e_cups: YCB_065_E_CUPS
ycb_065_f_cups: YCB_065_F_CUPS
ycb_065_g_cups: YCB_065_G_CUPS
ycb_065_h_cups: YCB_065_H_CUPS
ycb_065_i_cups: YCB_065_I_CUPS
ycb_065_j_cups: YCB_065_J_CUPS
ycb_070_a_colored_wood_blocks: YCB_070_A_COLORED_WOOD_BLOCKS
ycb_070_b_colored_wood_blocks: YCB_070_B_COLORED_WOOD_BLOCKS
ycb_071_nine_hole_peg_test: YCB_071_NINE_HOLE_PEG_TEST
ycb_072_a_toy_airplane: YCB_072_A_TOY_AIRPLANE
ycb_072_b_toy_airplane: YCB_072_B_TOY_AIRPLANE
ycb_072_c_toy_airplane: YCB_072_C_TOY_AIRPLANE
ycb_072_d_toy_airplane: YCB_072_D_TOY_AIRPLANE
ycb_072_e_toy_airplane: YCB_072_E_TOY_AIRPLANE
ycb_073_a_lego_duplo: YCB_073_A_LEGO_DUPLO
ycb_073_b_lego_duplo: YCB_073_B_LEGO_DUPLO
ycb_073_c_lego_duplo: YCB_073_C_LEGO_DUPLO
ycb_073_d_lego_duplo: YCB_073_D_LEGO_DUPLO
ycb_073_e_lego_duplo: YCB_073_E_LEGO_DUPLO
ycb_073_f_lego_duplo: YCB_073_F_LEGO_DUPLO
ycb_073_g_lego_duplo: YCB_073_G_LEGO_DUPLO
ycb_077_rubiks_cube: YCB_077_RUBIKS_CUBE
